version: '3.7'

services:
  mnk-telegram-bot:
    container_name: mnk-telegram-bot
    ports:
      - '3000:3000'
    image: 034992998866.dkr.ecr.us-east-1.amazonaws.com/mnk-telegram-bot:latest
    volumes:
      - app-data:/data
    networks:
      - cloud-public
    environment:
      - NODE_ENV=production
    deploy:
#      placement:
#        constraints:
#          - node.hostname != n2.asy.ai
      labels:
        - traefik.enable=true
        - traefik.docker.network=cloud-public
        - traefik.constraint-label=cloud-public
        - traefik.http.services.mnk-telegram-bot.loadbalancer.server.port=3000
        - traefik.http.routers.mnk-telegram-bot-http.rule=Host(`orderflow.b4.uz`)
        - traefik.http.routers.mnk-telegram-bot-http.entrypoints=http
        - traefik.http.routers.mnk-telegram-bot-https.rule=Host(`orderflow.b4.uz`)
        - traefik.http.routers.mnk-telegram-bot-https.entrypoints=https
        - traefik.http.routers.mnk-telegram-bot-https.tls=true
        - traefik.http.routers.mnk-telegram-bot-https.tls.certresolver=le
        - traefik.http.routers.mnk-telegram-bot-http.middlewares=https-redirect

volumes:
  app-data:

networks:
  cloud-public:
    external: true
