version: '3.7'

services:
  app:
    image: 034992998866.dkr.ecr.us-east-1.amazonaws.com/asy-ui:latest
    volumes:
      - app-data:/data
    networks:
      - cloud-public
    environment:
      - NODE_ENV=production
    deploy:
      placement:
        constraints:
          - node.hostname != n2.asy.ai
      labels:
        - traefik.enable=true
        - traefik.docker.network=cloud-public
        - traefik.constraint-label=cloud-public
        - traefik.http.services.app.loadbalancer.server.port=3000
        - traefik.http.routers.app-http.rule=Host(`orderflow.b4.uz`)
        - traefik.http.routers.app-http.entrypoints=http
        - traefik.http.routers.app-https.rule=Host(`orderflow.b4.uz`)
        - traefik.http.routers.app-https.entrypoints=https
        - traefik.http.routers.app-https.tls=true
        - traefik.http.routers.app-https.tls.certresolver=le
        - traefik.http.middlewares.app-redirectregex.redirectregex.regex=^https?://orderflow.b4.uz/?(.*)
        - traefik.http.middlewares.app-redirectregex.redirectregex.replacement=https://www.orderflow.b4.uz/$${1}
        - traefik.http.routers.app-https.middlewares=app-redirectregex
        - traefik.http.routers.app-http.middlewares=https-redirect,app-redirectregex

volumes:
  app-data:

networks:
  cloud-public:
    external: true
